version: '3'

services:

  rabbitmqmaster:
    image: rabbitmq:3-management
    hostname: rabbitmqmaster
    environment:
      - RABBITMQ_ERLANG_COOKIE=12345
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  rabbitmq1:
        image: rabbitmq:3-management
        hostname: rabbitmq1
        depends_on:
          - rabbitmqmaster
        environment:
          - RABBITMQ_ERLANG_COOKIE=12345
        links:
            - rabbitmqmaster
        volumes:
          - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
        entrypoint: /usr/local/bin/cluster-entrypoint.sh
  rabbitmq2:
        image: rabbitmq:3-management
        hostname: rabbitmq2
        depends_on:
          - rabbitmqmaster
        environment:
          - RABBITMQ_ERLANG_COOKIE=12345
        links:
            - rabbitmqmaster
        volumes:
          - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
        entrypoint: /usr/local/bin/cluster-entrypoint.sh
  haproxy:
        image: haproxy:1.7
        ports:
            -  8080:15672
            -  5672:5672
        volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        links:
            - rabbitmqmaster
            - rabbitmq1
            - rabbitmq2
        depends_on:
         - rabbitmqmaster
         - rabbitmq1
         - rabbitmq2